version: '3.9'
services:
  kredis:
        hostname: kredis
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        ports:
            - "6379:6379"  
        restart: unless-stopped

        profiles:
          - "dev" 
  trado-web:
    container_name: trado-web
    build:
      context: ./trado-web
    ports:
      - '5000:5000'
    volumes: 
      - './trado-web:/src'
    environment: 
      # set environment variables
      REDISTOGO_URL: redis://kredis:6379/
      #DEV_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      #TEST_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      #DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    command: honcho start

    profiles:
      - "dev"
      - "test"

    restart: always

    depends_on:
      - kredis
      
  

   
