from flask_wtf import FlaskForm
from wtforms.fields import SelectField, SubmitField
from wtforms_alchemy import ModelForm, model_form_factory

from app.common.flask_uploads import IMAGES, UploadSet

BaseModelForm = model_form_factory(FlaskForm)

images = UploadSet('images', IMAGES)


class SeekingForm(BaseModelForm):

    seeking_partner = SelectField(' Type of partner', choices=[
        ('A Date', 'A Date'),
        ('A Marriage Partner', 'A Marriage Partner'),
        ('Open to Chat', 'Open to Chat'),
        ('Live together', 'Live together')])

    seeking_from_height = SelectField(' From ', choices=[
        ('4 feet', '4 feet'),
        ('4 feet 1 inches', '4 feet 1 inches'),
        ('4 feet 2 inches', '4 feet 2 inches'),
        ('4 feet 3 inches', '4 feet 3 inches'),
        ('4 feet 4 inches', '4 feet 4 inches'),
        ('4 feet 5 inches', '4 feet 5 inches'),
        ('4 feet 6 inches', '4 feet 6 inches'),
        ('4 feet 7 inches', '4 feet 7 inches'),
        ('4 feet 8 inches', '4 feet 8 inches'),
        ('4 feet 9 inches', '4 feet 9 inches'),
        ('4 feet 10 inches', '4 feet 10 inches'),
        ('4 feet 11 inches', '4 feet 11 inches'),
        ('5 feet', '5 feet'),
        ('5 feet 1 inches', '5 feet 1 inches'),
        ('5 feet 2 inches', '5 feet 2 inches'),
        ('5 feet 3 inches', '5 feet 3 inches'),
        ('5 feet 4 inches', '5 feet 4 inches'),
        ('5 feet 5 inches', '5 feet 5 inches'),
        ('5 feet 6 inches', '5 feet 6 inches'),
        ('5 feet 7 inches', '5 feet 7 inches'),
        ('5 feet 8 inches', '5 feet 8 inches'),
        ('5 feet 9 inches', '5 feet 9 inches'),
        ('5 feet 10 inches', '5 feet 10 inches'),
        ('5 feet 11 inches', '5 feet 11 inches'),
        ('6 feet', '6 feet'),
        ('6 feet 1 inches', '6 feet 1 inches'),
        ('6 feet 2 inches', '6 feet 2 inches'),
        ('6 feet 3 inches', '6 feet 3 inches'),
        ('6 feet 4 inches', '6 feet 4 inches'),
        ('6 feet 5 inches', '6 feet 5 inches'),
        ('6 feet 6 inches', '6 feet 6 inches'),
        ('6 feet 7 inches', '6 feet 7 inches'),
        ('6 feet 8 inches', '6 feet 8 inches'),
        ('6 feet 9 inches', '6 feet 9 inches'),
        ('6 feet 10 inches', '6 feet 10 inches'),
        ('6 feet 11 inches', '6 feet 11 inches'),
        ('7 feet', '7 feet'),
        ('7 feet 1 inches', '7 feet 1 inches'),
        ('7 feet 2 inches', '7 feet 2 inches'),
        ('7 feet 3 inches', '7 feet 3 inches'),
        ('7 feet 4 inches', '7 feet 4 inches'),
        ('7 feet 5 inches', '7 feet 5 inches'),
        ('7 feet 6 inches', '7 feet 6 inches'),
        ('7 feet 7 inches', '7 feet 7 inches'),
        ('7 feet 8 inches', '7 feet 8 inches'),
        ('7 feet 9 inches', '7 feet 9 inches'),
        ('7 feet 10 inches', '7 feet 10 inches'),
        ('7 feet 11 inches', '7 feet 11 inches'),
        ('8 feet', '8 feet')])

    seeking_to_height = SelectField(' to height ', choices=[
        ('4 feet', '4 feet'),
        ('4 feet 1 inches', '4 feet 1 inches'),
        ('4 feet 2 inches', '4 feet 2 inches'),
        ('4 feet 3 inches', '4 feet 3 inches'),
        ('4 feet 4 inches', '4 feet 4 inches'),
        ('4 feet 5 inches', '4 feet 5 inches'),
        ('4 feet 6 inches', '4 feet 6 inches'),
        ('4 feet 7 inches', '4 feet 7 inches'),
        ('4 feet 8 inches', '4 feet 8 inches'),
        ('4 feet 9 inches', '4 feet 9 inches'),
        ('4 feet 10 inches', '4 feet 10 inches'),
        ('4 feet 11 inches', '4 feet 11 inches'),
        ('5 feet', '5 feet'),
        ('5 feet 1 inches', '5 feet 1 inches'),
        ('5 feet 2 inches', '5 feet 2 inches'),
        ('5 feet 3 inches', '5 feet 3 inches'),
        ('5 feet 4 inches', '5 feet 4 inches'),
        ('5 feet 5 inches', '5 feet 5 inches'),
        ('5 feet 6 inches', '5 feet 6 inches'),
        ('5 feet 7 inches', '5 feet 7 inches'),
        ('5 feet 8 inches', '5 feet 8 inches'),
        ('5 feet 9 inches', '5 feet 9 inches'),
        ('5 feet 10 inches', '5 feet 10 inches'),
        ('5 feet 11 inches', '5 feet 11 inches'),
        ('6 feet', '6 feet'),
        ('6 feet 1 inches', '6 feet 1 inches'),
        ('6 feet 2 inches', '6 feet 2 inches'),
        ('6 feet 3 inches', '6 feet 3 inches'),
        ('6 feet 4 inches', '6 feet 4 inches'),
        ('6 feet 5 inches', '6 feet 5 inches'),
        ('6 feet 6 inches', '6 feet 6 inches'),
        ('6 feet 7 inches', '6 feet 7 inches'),
        ('6 feet 8 inches', '6 feet 8 inches'),
        ('6 feet 9 inches', '6 feet 9 inches'),
        ('6 feet 10 inches', '6 feet 10 inches'),
        ('6 feet 11 inches', '6 feet 11 inches'),
        ('7 feet', '7 feet'),
        ('7 feet 1 inches', '7 feet 1 inches'),
        ('7 feet 2 inches', '7 feet 2 inches'),
        ('7 feet 3 inches', '7 feet 3 inches'),
        ('7 feet 4 inches', '7 feet 4 inches'),
        ('7 feet 5 inches', '7 feet 5 inches'),
        ('7 feet 6 inches', '7 feet 6 inches'),
        ('7 feet 7 inches', '7 feet 7 inches'),
        ('7 feet 8 inches', '7 feet 8 inches'),
        ('7 feet 9 inches', '7 feet 9 inches'),
        ('7 feet 10 inches', '7 feet 10 inches'),
        ('7 feet 11 inches', '7 feet 11 inches'),
        ('8 feet', '8 feet')])

    seeking_from_age = SelectField(u'From age', choices=[

        ('18', '18'),
        ('19', '19'),
        ('20', '20'),
        ('21', '21'),
        ('22', '22'),
        ('23', '23'),
        ('24', '24'),
        ('25', '25'),
        ('26', '26'),
        ('27', '27'),
        ('28', '28'),
        ('29', '29'),
        ('30', '30'),
        ('31', '31'),
        ('32', '32'),
        ('33', '33'),
        ('34', '34'),
        ('35', '35'),
        ('36', '36'),
        ('37', '37'),
        ('38', '38'),
        ('39', '39'),
        ('40', '40'),
        ('41', '41'),
        ('42', '42'),
        ('43', '43'),
        ('44', '44'),
        ('45', '45'),
        ('46', '46'),
        ('47', '47'),
        ('48', '48'),
        ('49', '49'),
        ('50', '50'),
        ('51', '51'),
        ('52', '52'),
        ('53', '53'),
        ('54', '54'),
        ('55', '55'),
        ('56', '56'),
        ('57', '57'),
        ('58', '58'),
        ('59', '59'),
        ('60', '60'),
        ('61', '61'),
        ('62', '62'),
        ('63', '63'),
        ('64', '64'),
        ('65', '65'),
        ('66', '66'),
        ('67', '67'),
        ('68', '68'),
        ('69', '69'),
        ('70', '70'),
        ('71', '71'),
        ('72', '72'),
        ('73', '73'),
        ('74', '74'),
        ('75', '75'),
        ('76', '76'),
        ('77', '77'),
        ('78', '78'),
        ('79', '79'),
        ('80', '80'),
        ('81', '81'),
        ('82', '82'),
        ('83', '83'),
        ('84', '84'),
        ('85', '85'),
        ('86', '86'),
        ('87', '87'),
        ('88', '88'),
        ('89', '89'),
        ('90', '90'),
        ('91', '91'),
        ('92', '92'),
        ('93', '93'),
        ('94', '94'),
        ('95', '95'),
        ('96', '96'),
        ('97', '97'),
        ('98', '98'),
        ('99', '99'),
        ('100', '100')])

    seeking_to_age = SelectField(u'To Age', choices=[
        ('18', '18'),
        ('19', '19'),
        ('20', '20'),
        ('21', '21'),
        ('22', '22'),
        ('23', '23'),
        ('24', '24'),
        ('25', '25'),
        ('26', '26'),
        ('27', '27'),
        ('28', '28'),
        ('29', '29'),
        ('30', '30'),
        ('31', '31'),
        ('32', '32'),
        ('33', '33'),
        ('34', '34'),
        ('35', '35'),
        ('36', '36'),
        ('37', '37'),
        ('38', '38'),
        ('39', '39'),
        ('40', '40'),
        ('41', '41'),
        ('42', '42'),
        ('43', '43'),
        ('44', '44'),
        ('45', '45'),
        ('46', '46'),
        ('47', '47'),
        ('48', '48'),
        ('49', '49'),
        ('50', '50'),
        ('51', '51'),
        ('52', '52'),
        ('53', '53'),
        ('54', '54'),
        ('55', '55'),
        ('56', '56'),
        ('57', '57'),
        ('58', '58'),
        ('59', '59'),
        ('60', '60'),
        ('61', '61'),
        ('62', '62'),
        ('63', '63'),
        ('64', '64'),
        ('65', '65'),
        ('66', '66'),
        ('67', '67'),
        ('68', '68'),
        ('69', '69'),
        ('70', '70'),
        ('71', '71'),
        ('72', '72'),
        ('73', '73'),
        ('74', '74'),
        ('75', '75'),
        ('76', '76'),
        ('77', '77'),
        ('78', '78'),
        ('79', '79'),
        ('80', '80'),
        ('81', '81'),
        ('82', '82'),
        ('83', '83'),
        ('84', '84'),
        ('85', '85'),
        ('86', '86'),
        ('87', '87'),
        ('88', '88'),
        ('89', '89'),
        ('90', '90'),
        ('91', '91'),
        ('92', '92'),
        ('93', '93'),
        ('94', '94'),
        ('95', '95'),
        ('96', '96'),
        ('97', '97'),
        ('98', '98'),
        ('99', '99'),
        ('100', '100')])

    seeking_religion = SelectField('Religion choice', choices=[
        ('Christianity', 'Christianity'),
        ('Judaism', 'Judaism'),
        ('Islam', 'Islam'),
        ('Hinduism', 'Hinduism'),
        ('None', 'None'),
        ('Others', 'Others'),
        ('MIxed', 'Mixed')
        ])


    seeking_ethnicity = SelectField('Seeking Ethnicity', choices=[
        ('African American', 'African American'),
        ('Caucasian', 'Caucasian'),
        ('European', 'European'),
        ('Hispanic', 'Hispanic'),
        ('Indian', 'Indian'),
        ('Middle Eastern', 'Middle Eastern'),
        ('African', 'African'),
        ('Native American (Indian)', 'Native American (Indian)'),
        ('Asian', 'Asian'),
        ('Pacific Islander', 'Pacific Islander'),
        ('Caribbean', 'Caribbean'),
        ('Mixed Race', 'Mixed Race'),
        ('Other Ethnicity', 'Other Ethnicity')
    ])
   
    seeking_marital_type = SelectField(' Seeking relationship preference', choices=[
        ('Monogamy', 'Monogamy'),
        ('Polygamy', 'Polygamy'),
        ('Both Polygamy or Monogamy', 'Both Polygamy or Monogamy')])


    seeking_body_type = SelectField('Seeking body type', choices=[
        ('Slender', 'Slender'),
        ('Athletic', 'Athletic'),
        ('Average', 'Average'),
        ('A Few Extra Pounds', 'A Few Extra Pounds'),
        ('Big & Tall/BBW', 'Big & Tall/BBW'),
        ('Muscular', 'Muscular'),

        ('Voluptuous', 'Voluptuous'),
        ('Petite', 'Petite'),
        ('Well Proportioned', 'Well Proportioned'),
        ('Curvy/Curvaceous', 'Curvy/Curvaceous')])

    seeking_drinking_status = SelectField(' drinking status', choices=[
        ('No', 'No'),
        ('Socially', 'Socially'),
        ('Ocassionally', 'Ocassionally'),
        ('Frequently', 'Frequently'),
        ('Daily', 'Daily')])

    seeking_smoking_status = SelectField(' smoking status', choices=[
        ('No', 'No'),
        ('Socially', 'Socially'),
        ('Ocassionally', 'Ocassionally'),
        ('Frequently', 'Frequently'),
        ('Daily', 'Daily')])

    seeking_education_level = SelectField('Education level', choices=[
        ('Some School', 'Some School'),
        ('GED', 'GED'),
        ('High School Graduate', 'High School Graduate'),
        ('Specialty/Trade School', 'Specialty/Trade School'),
        ('Some College', 'Some College'),

        ('2 Yr College Degree/Diploma', '2 Yr College Degree/Diploma'),
        ('4 Yr College Degree/Diploma', '4 Yr College Degree/Diploma'),
        ('Masters/Post Graduate Diploma', 'Masters/Post Graduate Diploma'),

        ('Ph.D./Doctorate', 'Ph.D./Doctorate')])

    seeking_has_children = SelectField(' has kids', choices=[
        ('Yes', 'Yes'),
        ('Yes but all grown', 'Yes but all grown'),
        ('No', 'No')])

    seeking_want_children = SelectField(' want kids', choices=[
        ('Yes', 'Yes'),
        ('Yes but all grown', 'Yes but all grown'),
        ('No', 'No')])

    

    seeking_open_for_relocation = SelectField(' relocation option', choices=[
        ('Yes', 'Yes'),
        ('Maybe ', 'Maybe'),
        ('No', 'No')])

    seeking_country = SelectField(u'Select Country ', choices=[

        ('Afganistan', 'Afghanistan'),
        ('Albania', 'Albania'),
        ('Algeria', 'Algeria'),
        ('American Samoa', 'American Samoa'),
        ('Andorra', 'Andorra'),
        ('Angola', 'Angola'),
        ('Anguilla', 'Anguilla'),
        ('Antigua & Barbuda', 'Antigua & Barbuda'),
        ('Argentina', 'Argentina'),
        ('Armenia', 'Armenia'),
        ('Aruba', 'Aruba'),
        ('Australia', 'Australia'),
        ('Austria', 'Austria'),
        ('Azerbaijan', 'Azerbaijan'),
        ('Bahamas', 'Bahamas'),
        ('Bahrain', 'Bahrain'),
        ('Bangladesh', 'Bangladesh'),
        ('Barbados', 'Barbados'),
        ('Belarus', 'Belarus'),
        ('Belgium', 'Belgium'),
        ('Belize', 'Belize'),
        ('Benin', 'Benin'),
        ('Bermuda', 'Bermuda'),
        ('Bhutan', 'Bhutan'),
        ('Bolivia', 'Bolivia'),
        ('Bonaire', 'Bonaire'),
        ('Bosnia & Herzegovina', 'Bosnia & Herzegovina'),
        ('Botswana', 'Botswana'),
        ('Brazil', 'Brazil'),
        ('British Indian Ocean Ter', 'British Indian Ocean Ter'),
        ('Brunei', 'Brunei'),
        ('Bulgaria', 'Bulgaria'),
        ('Burkina Faso', 'Burkina Faso'),
        ('Burundi', 'Burundi'),
        ('Cambodia', 'Cambodia'),
        ('Cameroon', 'Cameroon'),
        ('Canada', 'Canada'),
        ('Canary Islands', 'Canary Islands'),
        ('Cape Verde', 'Cape Verde'),
        ('Cayman Islands', 'Cayman Islands'),
        ('Central African Republic', 'Central African Republic'),
        ('Chad', 'Chad'),
        ('Channel Islands', 'Channel Islands'),
        ('Chile', 'Chile'),
        ('China', 'China'),
        ('Christmas Island', 'Christmas Island'),
        ('Cocos Island', 'Cocos Island'),
        ('Colombia', 'Colombia'),
        ('Comoros', 'Comoros'),
        ('Congo', 'Congo'),
        ('Cook Islands', 'Cook Islands'),
        ('Costa Rica', 'Costa Rica'),
        ('Cote DIvoire', 'Cote DIvoire'),
        ('Croatia', 'Croatia'),
        ('Cuba', 'Cuba'),
        ('Curaco', 'Curacao'),
        ('Cyprus', 'Cyprus'),
        ('Czech Republic', 'Czech Republic'),
        ('Denmark', 'Denmark'),
        ('Djibouti', 'Djibouti'),
        ('Dominica', 'Dominica'),
        ('Dominican Republic', 'Dominican Republic'),
        ('East Timor', 'East Timor'),
        ('Ecuador', 'Ecuador'),
        ('Egypt', 'Egypt'),
        ('El Salvador', 'El Salvador'),
        ('Equatorial Guinea', 'Equatorial Guinea'),
        ('Eritrea', 'Eritrea'),
        ('Estonia', 'Estonia'),
        ('Ethiopia', 'Ethiopia'),
        ('Falkland Islands', 'Falkland Islands'),
        ('Faroe Islands', 'Faroe Islands'),
        ('Fiji', 'Fiji'),
        ('Finland', 'Finland'),
        ('France', 'France'),
        ('French Guiana', 'French Guiana'),
        ('French Polynesia', 'French Polynesia'),
        ('French Southern Ter', 'French Southern Ter'),
        ('Gabon', 'Gabon'),
        ('Gambia', 'Gambia'),
        ('Georgia', 'Georgia'),
        ('Germany', 'Germany'),
        ('Ghana', 'Ghana'),
        ('Gibraltar', 'Gibraltar'),
        ('Great Britain', 'Great Britain'),
        ('Greece', 'Greece'),
        ('Greenland', 'Greenland'),
        ('Grenada', 'Grenada'),
        ('Guadeloupe', 'Guadeloupe'),
        ('Guam', 'Guam'),
        ('Guatemala', 'Guatemala'),
        ('Guinea', 'Guinea'),
        ('Guyana', 'Guyana'),
        ('Haiti', 'Haiti'),
        ('Hawaii', 'Hawaii'),
        ('Honduras', 'Honduras'),
        ('Hong Kong', 'Hong Kong'),
        ('Hungary', 'Hungary'),
        ('Iceland', 'Iceland'),
        ('Indonesia', 'Indonesia'),
        ('India', 'India'),
        ('Iran', 'Iran'),
        ('Iraq', 'Iraq'),
        ('Ireland', 'Ireland'),
        ('Isle of Man', 'Isle of Man'),
        ('Israel', 'Israel'),
        ('Italy', 'Italy'),
        ('Jamaica', 'Jamaica'),
        ('Japan', 'Japan'),
        ('Jordan', 'Jordan'),
        ('Kazakhstan', 'Kazakhstan'),
        ('Kenya', 'Kenya'),
        ('Kiribati', 'Kiribati'),
        ('Korea North', 'Korea North'),
        ('Korea Sout', 'Korea South'),
        ('Kuwait', 'Kuwait'),
        ('Kyrgyzstan', 'Kyrgyzstan'),
        ('Laos', 'Laos'),
        ('Latvia', 'Latvia'),
        ('Lebanon', 'Lebanon'),
        ('Lesotho', 'Lesotho'),
        ('Liberia', 'Liberia'),
        ('Libya', 'Libya'),
        ('Liechtenstein', 'Liechtenstein'),
        ('Lithuania', 'Lithuania'),
        ('Luxembourg', 'Luxembourg'),
        ('Macau', 'Macau'),
        ('Macedonia', 'Macedonia'),
        ('Madagascar', 'Madagascar'),
        ('Malaysia', 'Malaysia'),
        ('Malawi', 'Malawi'),
        ('Maldives', 'Maldives'),
        ('Mali', 'Mali'),
        ('Malta', 'Malta'),
        ('Marshall Islands', 'Marshall Islands'),
        ('Martinique', 'Martinique'),
        ('Mauritania', 'Mauritania'),
        ('Mauritius', 'Mauritius'),
        ('Mayotte', 'Mayotte'),
        ('Mexico', 'Mexico'),
        ('Midway Islands', 'Midway Islands'),
        ('Moldova', 'Moldova'),
        ('Monaco', 'Monaco'),
        ('Mongolia', 'Mongolia'),
        ('Montserrat', 'Montserrat'),
        ('Morocco', 'Morocco'),
        ('Mozambique', 'Mozambique'),
        ('Myanmar', 'Myanmar'),
        ('Nambia', 'Nambia'),
        ('Nauru', 'Nauru'),
        ('Nepal', 'Nepal'),
        ('Netherland Antilles', 'Netherland Antilles'),
        ('Netherlands', 'Netherlands (Holland, Europe)'),
        ('Nevis', 'Nevis'),
        ('New Caledonia', 'New Caledonia'),
        ('New Zealand', 'New Zealand'),
        ('Nicaragua', 'Nicaragua'),
        ('Niger', 'Niger'),
        ('Nigeria', 'Nigeria'),
        ('Niue', 'Niue'),
        ('Norfolk Island', 'Norfolk Island'),
        ('Norway', 'Norway'),
        ('Oman', 'Oman'),
        ('Pakistan', 'Pakistan'),
        ('Palau Island', 'Palau Island'),
        ('Palestine', 'Palestine'),
        ('Panama', 'Panama'),
        ('Papua New Guinea', 'Papua New Guinea'),
        ('Paraguay', 'Paraguay'),
        ('Peru', 'Peru'),
        ('Phillipines', 'Philippines'),
        ('Pitcairn Island', 'Pitcairn Island'),
        ('Poland', 'Poland'),
        ('Portugal', 'Portugal'),
        ('Puerto Rico', 'Puerto Rico'),
        ('Qatar', 'Qatar'),
        ('Republic of Montenegro', 'Republic of Montenegro'),
        ('Republic of Serbia', 'Republic of Serbia'),
        ('Reunion', 'Reunion'),
        ('Romania', 'Romania'),
        ('Russia', 'Russia'),
        ('Rwanda', 'Rwanda'),
        ('St Barthelemy', 'St Barthelemy'),
        ('St Eustatius', 'St Eustatius'),
        ('St Helena', 'St Helena'),
        ('St Kitts-Nevis', 'St Kitts-Nevis'),
        ('St Lucia', 'St Lucia'),
        ('St Maarten', 'St Maarten'),
        ('St Pierre & Miquelon', 'St Pierre & Miquelon'),
        ('St Vincent & Grenadines', 'St Vincent & Grenadines'),
        ('Saipan', 'Saipan'),
        ('Samoa', 'Samoa'),
        ('Samoa American', 'Samoa American'),
        ('San Marino', 'San Marino'),
        ('Sao Tome & Principe', 'Sao Tome & Principe'),
        ('Saudi Arabia', 'Saudi Arabia'),
        ('Senegal', 'Senegal'),
        ('Seychelles', 'Seychelles'),
        ('Sierra Leone', 'Sierra Leone'),
        ('Singapore', 'Singapore'),
        ('Slovakia', 'Slovakia'),
        ('Slovenia', 'Slovenia'),
        ('Solomon Islands', 'Solomon Islands'),
        ('Somalia', 'Somalia'),
        ('South Africa', 'South Africa'),
        ('Spain', 'Spain'),
        ('Sri Lanka', 'Sri Lanka'),
        ('Sudan', 'Sudan'),
        ('Suriname', 'Suriname'),
        ('Swaziland', 'Swaziland'),
        ('Sweden', 'Sweden'),
        ('Switzerland', 'Switzerland'),
        ('Syria', 'Syria'),
        ('Tahiti', 'Tahiti'),
        ('Taiwan', 'Taiwan'),
        ('Tajikistan', 'Tajikistan'),
        ('Tanzania', 'Tanzania'),
        ('Thailand', 'Thailand'),
        ('Togo', 'Togo'),
        ('Tokelau', 'Tokelau'),
        ('Tonga', 'Tonga'),
        ('Trinidad & Tobago', 'Trinidad & Tobago'),
        ('Tunisia', 'Tunisia'),
        ('Turkey', 'Turkey'),
        ('Turkmenistan', 'Turkmenistan'),
        ('Turks & Caicos Is', 'Turks & Caicos Is'),
        ('Tuvalu', 'Tuvalu'),
        ('Uganda', 'Uganda'),
        ('United Kingdom', 'United Kingdom'),
        ('Ukraine', 'Ukraine'),
        ('United Arab Erimates', 'United Arab Emirates'),
        ('United States of America', 'United States of America'),
        ('Uraguay', 'Uruguay'),
        ('Uzbekistan', 'Uzbekistan'),
        ('Vanuatu', 'Vanuatu'),
        ('Vatican City State', 'Vatican City State'),
        ('Venezuela', 'Venezuela'),
        ('Vietnam', 'Vietnam'),
        ('Virgin Islands (Brit)', 'Virgin Islands (Brit)'),
        ('Virgin Islands (USA)', 'Virgin Islands (USA)'),
        ('Wake Island', 'Wake Island'),
        ('Wallis & Futana Is', 'Wallis & Futana Is'),
        ('Yemen', 'Yemen'),
        ('Zaire', 'Zaire'),
        ('Zambia', 'Zambia'),
        ('Zimbabwe', 'Zimbabwe')])

    