#web: gunicorn --worker-class gevent  -w 3 -b 0.0.0.0:5000 --error-logfile="trado.err.log"  --log-level debug --worker-connections 3000 -t 30 --keep-alive 5 manage:app
devweb:pypy3 manage.py runserver
worker: python -u manage.py run-cron-worker
